const playerEnum = {
  ADD_PLAYER: "ADD_PLAYER",
  GET_PLAYERS: "GET_PLAYERS",
  GET_PLAYER_BY_ID: "GET_PLAYER_BY_ID",
  ADD_TRANSACTION: "ADD_TRANSACTION",
  BANK: "Bank",
  FREE_PARKING: "Free parking",
  ADD_SALARY: "ADD_SALARY",
  CLEAR_GAME: "CLEAR_GAME",
};

export default playerEnum;
